[component]
array_structures = [ "blocks" ]
label = "Component"
description = "Example bookshop top level component"
icon = "widgets"
tags = [ "Examples" ]

[props]
name = "Hello World"
subtext = "I am a subcomponent"
