[component]
array_structures = [ "blocks" ]
label = "Select"
description = "Example bookshop select"
icon = "arrow_drop_down"
tags = [ "Examples" ]

[props]
image.select = ["https://placekitten.com/200/100", "https://placekitten.com/100/200"]

