[component]
array_structures = [ "content_blocks" ]
label = "Testing Component"
description = "Description of testing component"
icon = "nature_people"
tags = [ "one", "two", "three" ]

[props]
title = "This is the title"           #: Used for the slug
big.default = false                   #: Whether to show the image or not
image.preview = ["/a.png", "b.jpg"]   #: Used when big: true
author.name = "Kubo"                  #: Original author
author.position.default = "Good Dog"  #: Position in company

[[props.sections]]                    #: Top level blog info
section_name = "Stats"                #: Navigation Label
alignment.select = ["left", "right"]  #: Useful to alternate
[[props.sections.tags]]               #: Tags are used in search results
tag_name.select = ["good", "great"]   #: Single word only
color.default = "#407AFC"             #: Not used on mobile

[props.category]                      #: Shown on archive pages
label = "Popular"                     #: Search label
weight_number = 10                    #: Higher weights bump post up in category