[component]
array_structures = [ "blocks" ]
label = "Comments"
description = "Example bookshop comments"
icon = "comment"
tags = [ "Examples" ]

[props]
title = "Hello World" #: Post Title
author.select = ["CloudCannon", 'Guest'] #: Post Author

[[props.tags]] #: Article Tags
tag = "SSG" #: Name of tag

