[component]
array_structures = [ "blocks" ]
label = "Object"
description = "Example bookshop object"
icon = "check_box_outline_blank"
tags = [ "Examples", "Structures" ]

[props]
post.title = "Hello world"
post.author = "CloudCannon"


