[component]
array_structures = [ "blocks" ]
label = "Preview"
description = "Example bookshop preview"
icon = "visibility_off"
tags = [ "Examples" ]

[props]
image.preview = ["https://placekitten.com/200/100", "https://placekitten.com/100/200"]

