[component]
array_structures = [ "blocks" ]
label = "Repeat"
description = "Example bookshop repeat"
icon = "view_agenda"
tags = [ "Examples", "Structures" ]

[props]

[[props.items]]
message = "Line item"
weight = 4

[[props.items]]
message = "Second Line item"
weight = 6
