baseURL = "https://bookshop.build/"
languageCode = "en-us"
title = "Hugo Bookshop Cucumber"
copyright = "🎉"

[module]
replacements = "bookshop.test/components -> ../../component-lib,github.com/cloudcannon/bookshop/hugo/v2 -> ../../../../../../hugo/v2/"

[[module.imports]]
path = 'bookshop.test/components'
