name: Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}

    env:
      cwd: ./javascript-modules

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Hugo 0.89
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.89.0"
          extended: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Use Ruby 2.7.x
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Use Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.6"
      - run: yarn install --immutable
        working-directory: ${{ env.cwd }}
      - name: Vendor node modules into ruby packages
        run: node ./scripts/publish.js vendor
      - name: Build Hugo wasm module
        run: go build -tags nodeploy -o hugo_renderer.wasm
        working-directory: ${{ env.cwd }}/engines/hugo-engine/hugo-renderer
        env:
          GOOS: js
          GOARCH: wasm
      - run: yarn run itest
        working-directory: ${{ env.cwd }}/integration-tests
