name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Swap to main
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0 # Full fetch
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.CC_OSS_BOT_ID }}
          application_private_key: ${{ secrets.CC_OSS_BOT_PEM }}
      
      - name: Use Hugo 0.89
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.89.0"
          extended: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      # TODO: Remove when possible (https://github.com/actions/setup-node/issues/515)
      - name: Windows Node fix
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $WhereNode = Get-Command node | Select-Object -ExpandProperty Definition
          $NodeDirPath = Split-Path $WhereNode -Parent
          cd $NodeDirPath
          npm install npm@8.12.1
      - name: Use Ruby 2.7.x
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Use Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.6"

      - run: yarn install --immutable
        working-directory: ./javascript-modules
      
      - name: Get Version
        run: echo GIT_VERSION="$(git describe --tags | sed 's/^v\(.*\)$/\1/')" >> $GITHUB_ENV
      - name: Verify Changelog
        run: |
          node ./.backstage/changelog.cjs
      - name: Ensure main / tag parity
        run: |
          [[ $(git tag --points-at HEAD) = "v$GIT_VERSION" ]] && echo "Main is at v$GIT_VERSION"
      
      - name: Update versions
        run: |
          node ./.backstage/version.js $GIT_VERSION
      - name: Vendor dependencies
        run: |
          node ./.backstage/vendor.js
      - name: Run tests
        run: |
          node ./.backstage/test.js
      - name: Run integration tests
        run : |
          yarn run itest-slow
        working-directory: ./javascript-modules/integration-tests
      
      - name: Publish
        run: |
          node ./.backstage/publish.js $GIT_VERSION seriously
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}

      - name: Build CHANGELOG
        run: |
          node ./.backstage/changelog.cjs write
          if test -f "RELEASE.md"; then
            echo HAS_RELEASE="true" >> $GITHUB_ENV
          fi
      
      - name: Update git
        run: |
          git config --global user.name "cloudcannon-oss[bot]"
          git config --global user.email "115603236+cloudcannon-oss[bot]@users.noreply.github.com"
          git add -A && git commit -m "build: releasing $GIT_VERSION"
          git tag -a hugo/v$GIT_VERSION -m "build: releasing $GIT_VERSION"
          git push && git push --tags

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        if: env.HAS_RELEASE == 'true'
        with:
          body_path: RELEASE.md
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
