name: Test Ruby Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set up jekyll-bookshop Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        working-directory: ./generator-plugins/jekyll/jekyll-bookshop
    - name: Set up cloudcannon-jekyll-bookshop Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        working-directory: ./generator-plugins/jekyll/cloudcannon-jekyll-bookshop
    - name: Run jekyll-bookshop tests
      run: bundle exec rake test
      working-directory: ./generator-plugins/jekyll/jekyll-bookshop
    - name: Run cloudcannon-jekyll-bookshop tests
      run: bundle exec rake test
      working-directory: ./generator-plugins/jekyll/cloudcannon-jekyll-bookshop
