name: Javascript Each

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  node-test:
    runs-on: ${{ matrix.os }}

    env:
      cwd: ./javascript-modules

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]
        package: [
          bookshop-sass,
          browser,
          builder,
          engines/eleventy-engine,
          engines/hugo-engine,
          engines/jekyll-engine,
          engines/svelte-engine,
          generate,
          generator-plugins/eleventy/eleventy-bookshop,
          generator-plugins/sveltekit/sveltekit-bookshop,
          helpers,
          init,
          integration-tests,
          live,
          styles,
          up
        ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Move yarn workspace package
        run: |
          mv package.json package.json.yarn
        working-directory: ${{ env.cwd }}
      - run: npm install
        working-directory: ${{ env.cwd }}/${{ matrix.package }}
      - name: Ugly fixes
        if: ${{ matrix.package == 'engines/svelte-engine' }}
        run: npm run testprep
      - run: npm test
        working-directory: ${{ env.cwd }}/${{ matrix.package }}
